### ISSUE TITLE
Fresh clone and yarn test fails after yarn reinstall

### ISSUE THREAD

**Issue by uivlis** [Charged-Particles/charged-particles-universe#39]
Pull from main, run `yarn reinstall && yarn compile && yarn test` and fail. Can you reproduce it @Elyx0 or it's supposed to be this way?

**Comment by Elyx0** [comment]
Might be that "incentives" has the correct tests and is ahead of main. No computer today to assess.

**Comment by uivlis** [comment]
Are you sure? I switched to the incentives branch, and the same tests fail in the same manner.
