### ISSUE TITLE
Why save "deployments" data in deploy scirpts?  

### ISSUE THREAD

**Issue by Lopol2010** [Charged-Particles/charged-particles-universe#53]
Plugin `hardhat-deploy` can save all this data automatically, could you please explain what's the reason to have your own system? Here is an example of what I mean:
```js
    deployData['ChargedParticles'] = {
      abi: getContractAbi('ChargedParticles'),
      address: chargedParticles.address,
      deployTransaction: chargedParticles.deployTransaction,
    }

    saveDeploymentData(chainId, deployData);
```
Similar question, why use ethers factory instead of `deploy` function from that plugin? I guess the reason will be the same, but who knows:)

**Comment by robsecord** [comment]
Because I wrote this code a long time ago when hardhat didn't save deployments data that I wanted to capture.
